(()=>{
if(document.getElementById('agendaModernUI23'))return;
const s=document.createElement('style');s.id='agendaModernUI23';s.textContent=`
:root{--violet:#8068f2;--violet2:#9b76f5;--pink:#ef9fc1;--peach:#ffb7aa;--dark:#151515;--panel:#202020;--paper:#fff9fb;--line:#eadde7;--blue:#38a4e8;--orange:#ffae36}
html,body{background:#e9e5f0!important;color:#26222d!important}.app{max-width:1900px;margin:auto;background:#e9e5f0!important;padding:16px!important}
header{position:sticky!important;top:0;background:#111!important;border-radius:22px 22px 0 0!important;border:0!important;box-shadow:0 15px 35px rgba(39,25,57,.18)!important;padding:8px 12px!important}
.toolbar{gap:9px!important;padding:8px!important}.toolbar:before{content:'AGENDA ELIP';color:white;font-weight:900;font-size:18px;letter-spacing:.06em;margin-right:12px}.toolbar button{background:#252525!important;color:#fff!important;border:1px solid #383838!important;border-radius:10px!important}.toolbar button.primary,#newEvent{background:linear-gradient(135deg,var(--violet),#a873ed)!important;border:0!important;color:#fff!important}.week-title{color:#fff!important;padding:2px 12px 10px!important}
.calendar-wrap{margin:12px 0 0!important;border:0!important;border-radius:0 0 20px 20px!important;background:linear-gradient(135deg,#9a80f4 0%,#efa1c1 55%,#f8b2ad 100%)!important;padding:18px!important;box-shadow:0 18px 40px rgba(53,31,78,.18)!important}.calendar{background:rgba(255,250,253,.90)!important;border-radius:17px!important;overflow:hidden!important}.head{background:rgba(255,255,255,.20)!important;color:#fff!important;border-color:rgba(255,255,255,.25)!important;font-weight:800!important}.head.weekend{background:rgba(255,170,181,.22)!important;color:#9c1d32!important}.time{background:#fff8fb!important;border-color:#eee2ea!important;color:#786d78!important}.cell{background:rgba(255,255,255,.83)!important;border-color:#eadde7!important}.cell.weekend{background:rgba(255,239,243,.88)!important}.cell:hover{background:#fff!important}.event{color:white!important;border:0!important;border-radius:9px!important;box-shadow:0 5px 12px rgba(75,48,105,.13)!important;font-weight:700!important}.event.low{background:linear-gradient(135deg,#38a4e8,#2e94dc)!important}.event.medium{background:linear-gradient(135deg,#8b72f5,#8063ed)!important}.event.high{background:linear-gradient(135deg,#ffb33f,#ff9d2f)!important}
.notes-grid{gap:12px!important;padding:14px 0!important}.note-card{border:0!important;border-radius:15px!important;box-shadow:0 8px 20px rgba(48,32,64,.10)!important}.note-card h3{background:#211f25!important;color:#fff!important;padding:11px 14px!important}.note-card.green h3:before{content:'☎  '}.note-card.blue h3:before{content:'✎  '}.note-card.orange h3:before{content:'↗  '}.note-card textarea{background:#fff!important;border:0!important}.status{color:#6e6472!important}
button{border-radius:10px!important}dialog{border:0!important;border-radius:18px!important;box-shadow:0 30px 90px rgba(20,10,28,.35)!important}dialog::backdrop{background:rgba(18,12,23,.55)!important;backdrop-filter:blur(4px)}.modal{background:#fffafd!important}.modal h2{color:#4e3b64!important}input,select,textarea{border:1px solid #e3d9e4!important;border-radius:10px!important}input:focus,select:focus,textarea:focus{border-color:#8c70ef!important;box-shadow:0 0 0 3px rgba(140,112,239,.13)!important}.contacts-panel{background:#181818;color:#fff;border-radius:16px;padding:14px;margin:0 0 14px;box-shadow:0 10px 25px rgba(0,0,0,.14)}.contacts-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.contacts-head strong{font-size:16px}.contacts-panel button{background:#2b2b2b!important;color:#fff!important;border:1px solid #444!important;padding:7px 10px!important}.contact-list{display:grid;gap:7px;margin-top:10px}.contact-row{display:flex;align-items:center;gap:9px;background:#242424;border-radius:11px;padding:8px 10px}.contact-avatar{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#8c72f2,#ee9bbd);font-weight:800}.contact-info{flex:1;min-width:0}.contact-info b,.contact-info small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.contact-info small{color:#bcb6c0}.contact-row a{color:#bdafff;text-decoration:none;font-size:20px}.contact-form{display:grid;grid-template-columns:1fr 1fr auto;gap:7px;margin-top:10px}.contact-form input{background:#2a2a2a!important;color:#fff!important;border-color:#444!important;padding:8px!important}
@media(min-width:900px){.calendar{width:100%!important;min-width:0!important;grid-template-columns:72px repeat(7,minmax(105px,1fr))!important}.notes-grid{grid-template-columns:repeat(3,1fr)!important}.contacts-panel{max-width:430px}}
@media(max-width:700px){.app{padding:0!important}.toolbar:before{font-size:13px;margin-right:2px}.calendar-wrap{padding:8px!important;border-radius:0 0 14px 14px!important}.contact-form{grid-template-columns:1fr 1fr}.contact-form button{grid-column:1/-1}}
`;document.head.appendChild(s);
function contactsUI(){if(document.querySelector('.contacts-panel'))return;const notes=document.querySelector('.notes-grid');if(!notes)return;const p=document.createElement('section');p.className='contacts-panel';p.innerHTML=`<div class="contacts-head"><strong>👥 Contatti telefonici</strong><button type="button" id="contactToggle">＋ Contatto</button></div><div class="contact-form" id="contactForm" style="display:none"><input id="contactName" placeholder="Nome"><input id="contactPhone" type="tel" placeholder="Telefono"><button id="contactSave" type="button">Salva</button></div><div class="contact-list" id="contactList"></div>`;notes.parentNode.insertBefore(p,notes);const key='agendaElipContacts';const load=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};const draw=()=>{const a=load(),l=document.getElementById('contactList');l.innerHTML=a.length?a.map((c,i)=>`<div class="contact-row"><span class="contact-avatar">${(c.name||'?').trim().charAt(0).toUpperCase()}</span><span class="contact-info"><b>${esc(c.name)}</b><small>${esc(c.phone)}</small></span><a href="tel:${encodeURIComponent(c.phone)}" title="Chiama">☎</a><button type="button" data-del="${i}" title="Elimina">×</button></div>`).join(''):'<small style="color:#aaa">Nessun contatto salvato</small>';l.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const x=load();x.splice(+b.dataset.del,1);localStorage.setItem(key,JSON.stringify(x));draw()})};const esc=x=>String(x||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));document.getElementById('contactToggle').onclick=()=>{const f=document.getElementById('contactForm');f.style.display=f.style.display==='none'?'grid':'none'};document.getElementById('contactSave').onclick=()=>{const n=document.getElementById('contactName'),t=document.getElementById('contactPhone');if(!n.value.trim()||!t.value.trim())return;const a=load();a.push({name:n.value.trim(),phone:t.value.trim()});localStorage.setItem(key,JSON.stringify(a));n.value='';t.value='';draw()};draw()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',contactsUI);else contactsUI();
})();