(()=>{
if(document.getElementById('agendaModernUI23'))return;
const s=document.createElement('style');s.id='agendaModernUI23';s.textContent=`
:root{--violet:#8068f2;--pink:#ef9fc1;--peach:#ffb7aa;--dark:#111}
html,body{background:#dedbe8!important;color:#26222d!important}.app{max-width:1900px;margin:auto;background:#111!important;padding:16px!important;border-radius:28px;box-shadow:0 18px 55px rgba(30,20,45,.22)}
.agenda-shell{display:grid;grid-template-columns:290px minmax(0,1fr);gap:12px}.agenda-main{min-width:0}.agenda-sidebar{background:#151515;color:#fff;border-radius:18px;padding:12px;display:flex;flex-direction:column;gap:11px}.side-brand{height:54px;border-radius:12px;background:linear-gradient(135deg,#765ff0,#9a7cf5);display:flex;align-items:center;gap:10px;padding:0 14px;font-size:18px;font-weight:900}.side-search{background:#222!important;color:#fff!important;border:1px solid #333!important;width:100%;box-sizing:border-box}.side-card{background:#222;border-radius:13px;padding:12px}.side-card h3{margin:0 0 9px;font-size:14px}.side-nav{display:grid;gap:7px}.side-nav button{width:100%;text-align:left;background:#222!important;color:#fff!important;border:1px solid #303030!important}.side-nav button.active{background:#765ff0!important}.side-contact-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px}.side-contact-actions button{font-size:11px;padding:7px!important}.side-contacts{display:grid;gap:6px;max-height:220px;overflow:auto;margin-top:8px}.side-contact{display:flex;align-items:center;gap:7px;padding:7px;background:#292929;border-radius:9px}.side-avatar{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#8c72f2,#ee9bbd);font-weight:800}.side-contact span{flex:1;min-width:0}.side-contact b,.side-contact small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.side-contact small{color:#aaa}.side-contact a{color:#bdafff;text-decoration:none;font-size:18px}
.postit-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.postit{min-height:88px;border:0!important;border-radius:4px 4px 10px 4px!important;padding:10px!important;color:#3b3340!important;font:600 13px/1.3 system-ui!important;resize:vertical;box-shadow:0 5px 12px rgba(0,0,0,.18);transform:rotate(-.5deg)}.postit:nth-child(even){transform:rotate(.7deg)}.postit-yellow{background:#ffe77a!important}.postit-pink{background:#ffb4d0!important}.postit-blue{background:#9bdcff!important}.postit-green{background:#bdeca9!important}
header{background:#111!important;border:0!important;padding:7px!important}.toolbar{gap:8px!important}.toolbar:before{content:'AGENDA';color:#fff;font-weight:900;margin-right:10px}.toolbar button{background:#252525!important;color:#fff!important;border:1px solid #383838!important}.toolbar button.primary,#newEvent{background:#8068f2!important;color:#fff!important;border:0!important}.week-title{color:#fff!important}.calendar-wrap{margin:8px 0 0!important;border:0!important;border-radius:18px!important;background:linear-gradient(135deg,#9278f3,#ef9fc1 56%,#ffb7aa)!important;padding:17px!important}.calendar{background:rgba(255,249,252,.91)!important;border-radius:16px!important;overflow:hidden!important}.head{background:rgba(255,255,255,.22)!important;font-weight:800!important}.time{background:#fff8fb!important}.cell{background:rgba(255,255,255,.84)!important;border-color:#eadde7!important}.event{color:#fff!important;border:0!important;border-radius:9px!important;font-weight:700!important;box-shadow:0 5px 12px rgba(60,35,90,.14)!important}.event.low{background:#38a4e8!important}.event.medium{background:#8068f2!important}.event.high{background:#ffae36!important}.notes-grid{gap:12px!important;padding:12px 0!important}.note-card{border:0!important;border-radius:13px!important}.note-card h3{background:#222!important;color:#fff!important}.contacts-panel{display:none!important}dialog{border:0!important;border-radius:18px!important}.modal{background:#fffafd!important}input,select,textarea{border-radius:10px!important}.calendar.agenda-day-mode{grid-template-columns:72px minmax(0,1fr)!important;min-width:0!important;width:100%!important}.calendar.agenda-day-mode>.agenda-day-hidden{display:none!important}.calendar.agenda-day-mode .cell{min-height:76px}
@media(min-width:900px){.calendar:not(.agenda-day-mode){width:100%!important;min-width:0!important;grid-template-columns:72px repeat(7,minmax(105px,1fr))!important}.notes-grid{grid-template-columns:repeat(3,1fr)!important}}
@media(max-width:850px){.app{padding:0!important;border-radius:0}.agenda-shell{display:block}.agenda-sidebar{border-radius:0 0 14px 14px;padding:8px}.side-brand{height:42px}.calendar-wrap{padding:8px!important}.toolbar:before{display:none}.postit-grid{grid-template-columns:repeat(2,1fr)}}
`;document.head.appendChild(s);
const esc=x=>String(x||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function clearDay(){const cal=document.querySelector('#calendar');if(!cal)return;cal.classList.remove('agenda-day-mode');[...cal.children].forEach(x=>x.classList.remove('agenda-day-hidden'))}
function showDay(){const cal=document.querySelector('#calendar');if(!cal||cal.children.length<9)return;clearDay();const today=new Date(),iso=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;let dayCol=-1;[...cal.querySelectorAll('.cell')].some(c=>{if(c.dataset.date===iso){dayCol=[...cal.children].indexOf(c)%8;return true}return false});if(dayCol<1)dayCol=1;cal.classList.add('agenda-day-mode');[...cal.children].forEach((el,i)=>{const col=i%8;if(i!==0&&col!==0&&col!==dayCol)el.classList.add('agenda-day-hidden')})}
function parseVCF(text){const out=[];text.split(/END:VCARD/i).forEach(card=>{const n=(card.match(/(?:^|\n)FN[^:]*:(.*)/i)||[])[1];const tels=[...card.matchAll(/(?:^|\n)TEL[^:]*:(.*)/ig)].map(m=>m[1].trim());if(n)tels.forEach(phone=>out.push({name:n.trim(),phone}))});return out}
function build(){if(document.querySelector('.agenda-shell'))return;const app=document.querySelector('.app')||document.body,children=[...app.children],shell=document.createElement('div');shell.className='agenda-shell';const side=document.createElement('aside');side.className='agenda-sidebar';side.innerHTML=`<div class="side-brand">✦ <span>Agenda</span></div><input class="side-search" id="sideSearch" placeholder="Cerca qui"><div class="side-card"><h3>Calendario</h3><div class="side-nav"><button data-view="day">▣ Giorno</button><button data-view="week" class="active">▦ Settimana</button><button data-view="month">▦ Mese</button><button data-view="year">▦ Anno</button></div></div><div class="side-card"><h3>Note rapide</h3><div class="postit-grid"><textarea class="postit postit-yellow" data-p="0" placeholder="Scrivi nota..."></textarea><textarea class="postit postit-pink" data-p="1" placeholder="Scrivi nota..."></textarea><textarea class="postit postit-blue" data-p="2" placeholder="Scrivi nota..."></textarea><textarea class="postit postit-green" data-p="3" placeholder="Scrivi nota..."></textarea></div></div><div class="side-card contacts-card"><h3>Contatti</h3><div class="side-contact-actions"><button id="pickDeviceContacts">📱 Rubrica</button><button id="importVcf">⬆ Importa .VCF</button><button id="manualContact">＋ Manuale</button></div><input id="vcfFile" type="file" accept=".vcf,text/vcard,text/x-vcard" hidden><div id="manualFields" style="display:none;margin-top:7px"><input id="cn" placeholder="Nome" style="width:43%"><input id="cp" type="tel" placeholder="Telefono" style="width:43%"><button id="cs">Salva</button></div><div class="side-contacts" id="sideContacts"></div></div>`;const main=document.createElement('main');main.className='agenda-main';app.insertBefore(shell,app.firstChild);shell.append(side,main);children.forEach(x=>main.appendChild(x));
const key='agendaElipContacts',load=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}},save=a=>localStorage.setItem(key,JSON.stringify(a)),draw=()=>{const a=load(),l=side.querySelector('#sideContacts');l.innerHTML=a.length?a.map(c=>`<div class="side-contact"><i class="side-avatar">${esc((c.name||'?')[0]).toUpperCase()}</i><span><b>${esc(c.name)}</b><small>${esc(c.phone)}</small></span><a href="tel:${encodeURIComponent(c.phone)}">☎</a></div>`).join(''):'<small style="color:#999">Nessun contatto</small>'};
side.querySelectorAll('.postit').forEach(t=>{t.value=localStorage.getItem('agendaPostit'+t.dataset.p)||'';t.oninput=()=>localStorage.setItem('agendaPostit'+t.dataset.p,t.value)});
side.querySelector('#manualContact').onclick=()=>{const f=side.querySelector('#manualFields');f.style.display=f.style.display==='none'?'block':'none'};side.querySelector('#cs').onclick=()=>{const n=side.querySelector('#cn'),p=side.querySelector('#cp');if(!n.value.trim()||!p.value.trim())return;const a=load();a.push({name:n.value.trim(),phone:p.value.trim()});save(a);n.value=p.value='';draw()};
side.querySelector('#pickDeviceContacts').onclick=async()=>{if(navigator.contacts?.select){try{const picked=await navigator.contacts.select(['name','tel'],{multiple:true}),a=load();picked.forEach(c=>{const name=c.name?.[0]||'Contatto';(c.tel||[]).forEach(phone=>a.push({name,phone}))});save(a);draw();return}catch(e){}}alert('Su iPhone/Safari una pagina web non può leggere direttamente la Rubrica Apple. Ho aggiunto “Importa .VCF”: esporta/seleziona un file contatti .vcf e Agenda importerà nomi e numeri.')};
side.querySelector('#importVcf').onclick=()=>side.querySelector('#vcfFile').click();side.querySelector('#vcfFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const arr=parseVCF(await f.text()),a=load();arr.forEach(c=>{if(!a.some(x=>x.name===c.name&&x.phone===c.phone))a.push(c)});save(a);draw();alert(`Importati ${arr.length} contatti`)};
side.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='day'){showDay();return}clearDay();if(v==='week'){if(typeof render==='function')render();return}const target=[...document.querySelectorAll('button')].find(x=>x!==b&&x.textContent.trim().toLowerCase().includes(v==='month'?'mese':'anno'));if(target)target.click()});side.querySelector('#sideSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.event').forEach(el=>el.style.opacity=!q||el.textContent.toLowerCase().includes(q)?'1':'.18')};draw()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();